version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ticket
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket

    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
